import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";
import { createCatalog } from "../src/index.js";
import { ulid } from "../src/ulid.js";
import { makeStripeStub } from "./stripe-stub.js";

/**
 * The ids `createProduct` / `createPrice` / `createProductFeature` /
 * `attachFeature` assign when the caller supplies none.
 *
 * Those ids are persisted by whatever store a consumer plugs in, and sent to
 * Stripe as `product_id` / `price_id` metadata, so a row written by an earlier
 * release and a row written by this one have to be the same KIND of id: the
 * same length, the same alphabet, and the same sort order.
 *
 * This file was written while the implementation was still the `ulid` package
 * (2.4.0), and it passed there before the package was replaced. The literal
 * vectors below were produced BY that package, and the first one is the ULID
 * spec's own example, so they are an oracle that does not depend on the code
 * under test.
 *
 * What is pinned is what `ulid()` from that package did, which is NOT
 * monotonic within a millisecond (only its separate `monotonicFactory` was).
 * Nothing in this package orders by id — `order` exists for display sequence —
 * and the Python twin makes the same choice.
 */

const ULID = /^[0-9A-HJKMNP-TV-Z]{26}$/;
const TIME_MAX = 2 ** 48 - 1;

/** [timestamp ms, the first 10 characters `ulid` 2.4.0 produced for it] */
const TIME_VECTORS: Array<[number, string]> = [
  [1469918176385, "01ARYZ6S41"], // the example in the ULID spec
  [0, "0000000000"],
  [1, "0000000001"],
  [31, "000000000Z"],
  [32, "0000000010"],
  [Date.UTC(2026, 8, 13), "01M2C10K00"],
  [Date.UTC(2026, 8, 13) + 1, "01M2C10K01"],
  [TIME_MAX, "7ZZZZZZZZZ"],
];

/** Whole ids generated by `ulid` 2.4.0 — i.e. rows a consumer may already hold. */
const LEGACY_IDS: Array<[number, string]> = [
  [1469918176385, "01ARYZ6S41H7GT2EDX9NDPB37P"],
  [Date.UTC(2026, 8, 13), "01M2C10K001SNCQ5HCZ5706KAP"],
  [Date.UTC(2026, 8, 13) + 1, "01M2C10K01EKJD8SHK5M30W9JP"],
];

describe("ulid", () => {
  it("is 26 characters of Crockford base32 — no I, L, O or U, upper case", () => {
    for (let i = 0; i < 500; i++) expect(ulid()).toMatch(ULID);
  });

  it("encodes the millisecond timestamp into the first 10 characters exactly as before", () => {
    for (const [ms, prefix] of TIME_VECTORS) {
      const id = ulid(ms);
      expect(id, `timestamp ${ms}`).toMatch(ULID);
      expect(id.slice(0, 10), `timestamp ${ms}`).toBe(prefix);
    }
  });

  it("defaults to the current time", () => {
    const before = Date.now();
    const id = ulid();
    const after = Date.now();

    expect(id.slice(0, 10) >= ulid(before).slice(0, 10)).toBe(true);
    expect(id.slice(0, 10) <= ulid(after).slice(0, 10)).toBe(true);
  });

  it("interleaves with ids the previous implementation generated, by time", () => {
    for (const [ms, legacy] of LEGACY_IDS) {
      expect(legacy).toMatch(ULID);
      expect(ulid(ms).slice(0, 10)).toBe(legacy.slice(0, 10));
      // A string sort is a time sort, across the two implementations.
      expect(legacy < ulid(ms + 1)).toBe(true);
      expect(ulid(ms - 1) < legacy).toBe(true);
    }
    expect([...LEGACY_IDS.map(([, id]) => id)].sort()).toEqual(LEGACY_IDS.map(([, id]) => id));
  });

  it("sorts ids from later milliseconds after earlier ones", () => {
    const ids = [5, 4, 3, 2, 1].map((offset) => ulid(Date.UTC(2026, 0, 1) + offset * 1000));
    expect([...ids].sort()).toEqual([...ids].reverse());
  });

  it("gives ids in the same millisecond the same prefix and different randomness", () => {
    const ms = Date.UTC(2026, 8, 13);
    const ids = new Set(Array.from({ length: 1000 }, () => ulid(ms)));

    expect(ids.size).toBe(1000);
    for (const id of ids) expect(id.slice(0, 10)).toBe("01M2C10K00");
  });

  it("draws the random part from the whole alphabet", () => {
    // A masking or indexing slip shows up as characters that never appear —
    // e.g. a random part that is only ever digits still matches the regex.
    const seen = new Set<string>();
    for (let i = 0; i < 400; i++) for (const ch of ulid(0).slice(10)) seen.add(ch);
    expect(seen.size).toBe(32);
  });

  it("refuses a timestamp that does not fit in 48 bits, is negative, or is fractional", () => {
    expect(() => ulid(TIME_MAX + 1)).toThrow();
    expect(() => ulid(-1)).toThrow();
    expect(() => ulid(1.5)).toThrow();
  });
});

describe("catalog ids", () => {
  it("assigns a ULID to every row created without an id, and keeps an id it is given", async () => {
    const { stripe } = makeStripeStub();
    const catalog = createCatalog({ stripe });

    const product = await catalog.createProduct({ name: "Pro" });
    const price = await catalog.createPrice({ productId: product.id, currency: "usd", unitAmount: 1000 });
    const feature = await catalog.createProductFeature({ key: "seats", name: "Seats" });
    const config = await catalog.attachFeature({ productId: product.id, productFeatureId: feature.id });

    for (const id of [product.id, price.id, feature.id, config.id]) expect(id).toMatch(ULID);
    expect((await catalog.createProduct({ id: "p-explicit", name: "Kept" })).id).toBe("p-explicit");
  });
});

describe("the ulid package", () => {
  it("is not installed, so nothing above can be exercising it", () => {
    // The control. Every test above passed against the package and passes
    // against the first-party generator, so a green run cannot say which it
    // proved without this.
    expect(() => createRequire(import.meta.url).resolve("ulid")).toThrow();
  });
});
